edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: website-hexo-container2#  项目名称
access: 'default'  #  秘钥别名

services:
  framework: #  服务名称
    component: fc  # 组件名称
    # actions:
    #   pre-deploy: # 在deploy之前运行
    #     # 先将 base镜像预热到缓存目录，--cache-dir 表示缓存目录，--image 表示base镜像，可以指定多个
    #     # 如果要使用nas，cicd.yaml中的 runnerConfig 要指定 nasConfig，并且将--cache-dir 指定成 nasnCofig.mountDir
    #     - run: warmer --image=registry.ap-southeast-1.aliyuncs.com/fc-demo/test:fengchongV1 --cache-dir=/mnt/image-cache
    #     # 使用缓存目录构建镜像
    #     - component: fc build --use-docker --dockerfile ./code/Dockerfile --cache-dir=/mnt/image-cache
    props: #  组件的属性值
      region: 'ap-southeast-1'
      service:
        name: 'website'
        description: "Serverless Devs Website Service"
        role: 'acs:ram::${config(AccountID)}:role/AliyunFcDefaultRole'
        vpcConfig:
          securityGroupId: sg-t4n5nw95hdwfi54tfnfr
          vSwitchIds:
            - vsw-t4nuz466iajxa47msm4ve
          vpcId: vpc-t4nj7i5625fmh3ncbdlze
      function:
        name: 'hexo-custom-container'
        description: "Serverless Devs Website hexo Function"
        codeUri: ./code
        memorySize: 512
        runtime: custom-container
        customContainerConfig:
          # image: 'registry-vpc.ap-southeast-1.aliyuncs.com/fc-demo2/serverless-terraform:${env(GIT_COMMIT)}'
          image: 'demo-registry-vpc.ap-southeast-1.cr.aliyuncs.com/fc-demo/demo-test:${env(GIT_COMMIT)_accelerated'
          instanceID: cri-5oxhfi7lrqd04eyt
        timeout: 30
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
