edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: website-hexo-container1       #  项目名称
access: 'default'  #  秘钥别名

services:
  framework: #  服务名称
    component: fc  # 组件名称
    actions:
      pre-deploy: # 在deploy之前运行
        # 代码拷贝到nas目录 
        - run: cp -r * /mnt/docker-build
          path: ./code
        # 指定nas目录作为context进行build
        - component: fc build --use-docker --dockerfile ./code/Dockerfile --context /mnt/docker-build
        # - component: fc build --use-docker --dockerfile ./code/Dockerfile
    props: #  组件的属性值
      region: 'ap-southeast-1'
      service:
        name: 'website'
        description: "Serverless Devs Website Service"
        role: 'acs:ram::${config(AccountID)}:role/AliyunFcDefaultRole'
      function:
        name: 'hexo-custom-container'
        description: "Serverless Devs Website hexo Function"
        codeUri: ./code
        memorySize: 512
        runtime: custom-container
        customContainerConfig:
          image: 'registry-vpc.ap-southeast-1.aliyuncs.com/fc-demo2/serverless-terraform:1.0'
        timeout: 30
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
